blank_issues_enabled: false

contact_links:
  - name: ğŸ› Report an Issue (Raycast Store)
    url: https://google.com
    about: Found a bug or problem? Please report it through the Raycast Store&apos;s bug reporting function.

  - name: ğŸ’¡ Request a Feature (Raycast Store)
    url: https://google.com
    about: Have an idea or feature request? Submit it directly via the Raycast Store feedback function.

  - name: ğŸ“– Roadmap
    url: https://github.com/smcnab1/raycast-extension-template/blob/main/ROADMAP.md
    about: Check the README and roadmap for existing features, usage details, and upcoming updates.
